#!/bin/bash
#####
#  __  __       ____            _       _
# |  \/  |_   _/ ___|  ___ _ __(_)_ __ | |_ ___  | Simple
# | |\/| | | | \___ \ / __| '__| | '_ \| __/ __| | Linux
# | |  | | |_| |___) | (__| |  | | |_) | |_\__ \ | Script
# |_|  |_|\__, |____/ \___|_|  |_| .__/ \__|___/ | Management
#         |___/                  |_|
# KawaiiPantsu - https://github.com/kawaiipantsu/myscripts
###############################################################
## MyScript Variables
MYSCRIPT_NAME=${0##*/}
MYSCRIPT_PATH=$(dirname $(dirname "$(realpath -s "$0")"))
MYSCRIPT_ETC="${MYSCRIPT_PATH}/etc"
MYSCRIPT_AVAILABLE="${MYSCRIPT_PATH}/bin-available"
MYSCRIPT_ENABLED="${MYSCRIPT_PATH}/bin-enabled"
