#!/bin/bash
#####
#  __  __       ____            _       _
# |  \/  |_   _/ ___|  ___ _ __(_)_ __ | |_ ___  | Simple
# | |\/| | | | \___ \ / __| '__| | '_ \| __/ __| | Linux
# | |  | | |_| |___) | (__| |  | | |_) | |_\__ \ | Script
# |_|  |_|\__, |____/ \___|_|  |_| .__/ \__|___/ | Management
#         |___/                  |_|
# KawaiiPantsu - https://github.com/kawaiipantsu/myscripts
###############################################################
## MyScript Logging settings
MYSCRIPT_SYSLOG=false
MYSCRIPT_LOG=false

## MyScript Print functions settings
MYSCRIPT_PRINT_USE_COLORS=true
MYSCRIPT_PRINT_INCL_TIMESTAMP=true