#!/bin/bash
#####
#  __  __       ____            _       _
# |  \/  |_   _/ ___|  ___ _ __(_)_ __ | |_ ___  | Simple
# | |\/| | | | \___ \ / __| '__| | '_ \| __/ __| | Linux
# | |  | | |_| |___) | (__| |  | | |_) | |_\__ \ | Script
# |_|  |_|\__, |____/ \___|_|  |_| .__/ \__|___/ | Management
#         |___/                  |_|
# KawaiiPantsu - https://github.com/kawaiipantsu/myscripts
###############################################################
## Include Default Settings
source ${MYSCRIPT_PATH}/etc/default-settings

## Include Global Variables
source ${MYSCRIPT_PATH}/etc/default-vars

## Include Easy Color Variables
source ${MYSCRIPT_PATH}/etc/default-colors

## Include Global Bash Functions
source ${MYSCRIPT_PATH}/etc/default-functions
