#!/bin/bash
#####
#  __  __       ____            _       _
# |  \/  |_   _/ ___|  ___ _ __(_)_ __ | |_ ___  | Simple
# | |\/| | | | \___ \ / __| '__| | '_ \| __/ __| | Linux
# | |  | | |_| |___) | (__| |  | | |_) | |_\__ \ | Script
# |_|  |_|\__, |____/ \___|_|  |_| .__/ \__|___/ | Management
#         |___/                  |_|
# KawaiiPantsu - https://github.com/kawaiipantsu/myscripts
###############################################################
## MyScript - Quick setup section :)
MYSCRIPT_PATH=$(dirname $(dirname "$(realpath -s "$0")"))
source ${MYSCRIPT_PATH}/etc/default-settings
source ${MYSCRIPT_PATH}/etc/default-vars
source ${MYSCRIPT_PATH}/etc/default-colors
source ${MYSCRIPT_PATH}/etc/default-functions
#############################################################

## Simple checking of dependencies
## This is only cool if you remember to update this script!
echo ${_WHITE}==[${_RESTORE} MyScript Check Dependencies ${_WHITE}]===
myscript_checkcmd dialog
myscript_checkcmd wmctrl