#!/bin/bash
#####
#  __  __       ____            _       _
# |  \/  |_   _/ ___|  ___ _ __(_)_ __ | |_ ___  | Simple
# | |\/| | | | \___ \ / __| '__| | '_ \| __/ __| | Linux
# | |  | | |_| |___) | (__| |  | | |_) | |_\__ \ | Script
# |_|  |_|\__, |____/ \___|_|  |_| .__/ \__|___/ | Management
#         |___/                  |_|
# KawaiiPantsu - https://github.com/kawaiipantsu/myscripts
###############################################################
## MYSCRIPT - SCRIPT DEFAULTS :)
##################################################################
## %%MYSCRIPTS_DESCRIPTION=Resize qterminal to 648p 16:9
## %%MYSCRIPTS_GROUP=Streaming
## %%MYSCRIPTS_GROUP=Terminal
export MYSCRIPT_PATH=$(dirname $(dirname "$(realpath -s "$0")"))
source ${MYSCRIPT_PATH}/etc/script-defaults
##################################################################

## BEGIN SCRIPT
## Sanity check
hash wmctrl 2>/dev/null || { echo >&2 "Missing command 'wmctrl', perhaps you need to install the package? Aborting."; exit 1; }

wmctrl -x -r "qterminal.qterminal" -e 0,-1,-1,1152,648
if hash qterm-setcenter 2>/dev/null; then
	qterm-setcenter
fi
