." Manpage for myscript-test.
." Use the following link to create issues related to correct errors or typos.
." https://github.com/kawaiipantsu/myscripts/issues

.TH myscript-test 1 "31 Okt 2021" "1.0" "A MyScript man page"
.SH NAME
myscript-test \- This is just a simple test man page for testing
.SH SYNOPSIS
myscript-test
.SH DESCRIPTION
myscript-test is just a simple file to test that the man page path system works when setup or run manually. There is nothing in this man page that can help you out with anything. And also this long description is simply just something i did to amuse myself and to add a little meat to the page view... But you are welcome to read it all, i highly doubt you will though. But who knows!
.SH OPTIONS
I dont accept any options.
.SH SEE ALSO
myscript-status(1), myscript-conf(1) 
.SH BUGS
No known bugs.
.SH AUTHOR
KawaiiPantsu (github.com/kawaiipantsu)