." Manpage for <COMMAND_NAME>.
." Use the following link to create issues related to correct errors or typos.
." https://github.com/kawaiipantsu/myscripts/issues

.TH <COMMAND_NAME> 1 "<DATE_CREATED>" "1.0" "A MyScript man page"
.SH NAME
<COMMAND_NAME> \- <COMMAND_DESCRIPTION_SHORT> 
.SH SYNOPSIS
<COMMAND_NAME> [ -switches | -e | -t | -c] [ -more [ input ] ]
.SH DESCRIPTION
<COMMAND_NAME> <COMMAND_DESCRIPTION_FULL>
.SH OPTIONS
The following options may be used with <COMMAND_NAME>:
.SH SEE ALSO
myscript-status(1), myscript-conf(1) 
.SH BUGS
No known bugs.
.SH AUTHOR
KawaiiPantsu (github.com/kawaiipantsu)